In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd

In [2]:
M= pd.read_csv("train.csv")
df = pd.DataFrame(M)
df = df[np.isfinite(df['Age'])]
df = df[np.isfinite(df['Fare'])]
columns_for_differencing = ['PassengerId','Name','Cabin','Embarked','Parch','SibSp','Ticket']
X_train = df.copy()[df.columns.difference(columns_for_differencing)]
X_train = X_train.apply(lambda sex: pd.factorize(sex, sort=False)[0])
X_traind = X_train[X_train.Survived == 0]
X_trains = X_train[X_train.Survived == 1]
X_traind = X_traind.values
X_trains = X_trains.values
X_train = X_train.values
print(X_train)

[[  0   0   0   0   0]
 [  1   1   1   1   1]
 [  2   2   0   1   1]
 ...
 [ 18 185   1   1   1]
 [  2 185   1   0   1]
 [ 34  65   0   0   0]]


In [3]:
l=X_train[:,0:4]
n=len(l[:,1])
print(n)

714


In [4]:
a= []
sigma = 0.2
# print(l[:,1])
n=len(l[:,1])
A = np.array([[0.00] * n] *n)
W = np.array([[0.00] * n] *n)
theta=np.linspace(0,10,n)
theta=np.array(theta)

for i in range(n):
    a.append(0)

len(theta)

714

In [5]:
def similarity(x,l,n):
    for i in range(0,n):
        a[i]=(np.exp(-(np.sqrt(np.sum((x-l[i,])**2)))/2*sigma**2))
    return(a)

for i in range(0,n):
    A[i,]=similarity(l[i,],l,n)

def dot_product(theta,A,m):
    return((theta@A[m,]))
dot_product(theta,A,2)

954.3989846553507

In [6]:
C=100
g = np.array([0.00] * n)

def dcost(theta,A,X_train,m):
    g1=(-X_train[m,4]*(A[m,]/(np.exp(-theta@A[m,])-1)))
    g2=(1-X_train[m,4])*(-1)*A[m,]*(1/(1+np.exp(-theta@A[m,])))
    return(C*(g1+g2)+theta)
#dcost(theta,A,X_train,89)

In [12]:
def gd():
    w = np.array([0.00] * n)
    for j in range(0,n):
        dw = np.array([0.00] * n)
        for i in range(0,n):
            d1 = dcost(theta,A,X_train,i)
            dw = (d1+dw)/n
            
        w=w-0.1*dw
    return(w)
Q=gd()

In [8]:
M1= pd.read_csv("test.csv")
df = pd.DataFrame(M1)
df = df[np.isfinite(df['Age'])]
df = df[np.isfinite(df['Fare'])]
columns_for_differencing = ['PassengerId','Name','Cabin','Embarked','Parch','SibSp','Ticket']
X_test = df.copy()[df.columns.difference(columns_for_differencing)]
X_test = X_test.apply(lambda sex: pd.factorize(sex, sort=False)[0])
X_test = X_test.values
# print(X_test)

In [19]:
l1=X_test
# print(l1)
m=len(X_test)
A1= np.array([[0.00] * m] *m)
def similarity2(x,l,n):
    for i in range(0,n):
        b=(np.exp(-(np.sqrt(np.sum((x-l[i,])**2)))/2*sigma**2))
    return(b)

for i in range(0,m):
    A1[i,]=similarity2(l1[i,],l1,m)
# print(A1)

In [21]:
print(len(Q))
print(len(A1))


714
331
